import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Halaman home</h1>

        {/* buat link */}
        <Link href={"/"}>
          <p>Home</p>
        </Link>
        <Link href={"/about"}>
          <p>About</p>
        </Link>
        <Link href={"/blog"}>
          <p>Blog</p>
        </Link>
      </main>
    </>
  )
}
